on: [push]

jobs:
  deploy-local:
    runs-on: self-hosted
    name: Deploy to Docker Desktop Kubernetes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Run kubectl command
        run: kubectl get pods -A
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./runner
        run: terraform init

      - name: Terraform Apply
        working-directory: ./runner
        run: terraform plan
